"""
Create ground truth binary geometry tensors from Geant4 JSON configuration files.

DESCRIPTION:
    Reads a JSON geometry file (generated by create_geometry.py) and converts it to:
    - 3D binary numpy tensor (128×128×128) for UNET training
    - 2D projections as stacked tensor (128×128×3: XY, XZ, YZ)

    Automatically detects environment (local/cluster) and saves to appropriate folders.

INPUT:
    JSON file with voxel structure from create_geometry.py

OUTPUT (Automatic):
    LOCAL ENVIRONMENT:
        3Dimensions/: tensor_3D_{metadatos}.npy (128×128×128, uint8)
        2Dimensions/: tensor_2D_{metadatos}.npy (128×128×3, uint8)
    
    CLUSTER ENVIRONMENT:
        /gpfs/projects/cms/dominguezs/data/ground_truth_data/3Dimensions/
        /gpfs/projects/cms/dominguezs/data/ground_truth_data/2Dimensions/

USAGE:
    # Automatic detection of environment and output paths
    python3 create_ground_truth_from_json.py --json geometry.json
    
    # Process multiple geometries
    python3 create_ground_truth_from_json.py --json geom1.json geom2.json geom3.json
"""

import json
import argparse
import numpy as np
import sys
from pathlib import Path
import os

# ===========================================================================
# ENVIRONMENT DETECTION AND PATH SETUP
# ===========================================================================
def detect_environment_and_paths():
    """Detect if running locally or on cluster, return all relevant paths."""
    # Ground truth output paths
    cluster_gt_base = Path("/gpfs/projects/cms/dominguezs/data/ground_truth_data")
    local_gt_base = Path("/home/samuel/Work/Muography_Denoising/MuonGeneration/data/ground_truth_data")
    
    # JSON input paths
    cluster_json_base = Path("/gpfs/users/dominguezs/Muography_Denoising/MuonGeneration/data/geometric_configurations_json")
    local_json_base = Path("/home/samuel/Work/Muography_Denoising/MuonGeneration/data/geometric_configurations_json")
    
    if cluster_gt_base.exists():
        environment = "cluster"
        gt_base = cluster_gt_base
        json_base = cluster_json_base
    else:
        environment = "local"
        gt_base = local_gt_base
        json_base = local_json_base
    
    paths_3d = gt_base / "3Dimensions"
    paths_2d = gt_base / "2Dimensions"
    
    # Create directories if they don't exist
    paths_3d.mkdir(parents=True, exist_ok=True)
    paths_2d.mkdir(parents=True, exist_ok=True)
    
    return environment, paths_3d, paths_2d, json_base


def resolve_json_files(json_names, json_base):
    """Resolve JSON filenames to full paths in the geometric_configurations_json folder.
    
    Args:
        json_names: List of JSON filenames (e.g., ['geometry.json', 'test.json'])
        json_base: Path to the geometric_configurations_json folder
        
    Returns:
        List of full paths to JSON files
        
    Raises:
        SystemExit if JSON files not found
    """
    resolved_paths = []
    missing_files = []
    
    for json_name in json_names:
        # If user provided a path, use it; otherwise look in json_base
        if "/" in json_name or "\\" in json_name:
            # User provided a path
            json_path = Path(json_name)
        else:
            # User provided just a filename, look in json_base
            json_path = json_base / json_name
        
        if json_path.exists():
            resolved_paths.append(json_path)
        else:
            missing_files.append((json_name, json_path))
    
    if missing_files:
        error_msg = "[ERROR] JSON file(s) not found:\n"
        for original, full_path in missing_files:
            error_msg += f"  • {original} → searched in {full_path}\n"
        error_msg += f"\n[INFO] JSON folder: {json_base}\n"
        error_msg += f"[INFO] Make sure the files are in that directory"
        sys.exit(error_msg)
    
    return resolved_paths


def extract_metadata_from_json_filename(json_path):
    """Extract metadata from JSON filename to use in output filename."""
    json_file = Path(json_path).stem  # Remove .json extension
    # Remove leading underscores and preserve the full name as metadata
    if json_file.startswith("_"):
        metadata = json_file[1:]
    else:
        metadata = json_file
    return metadata


# ===========================================================================
# ARGUMENT PARSING
# ===========================================================================
parser = argparse.ArgumentParser(
    prog="create_ground_truth_from_json.py",
    description=(
        "Convert Geant4 JSON geometry files to binary 3D/2D numpy tensors.\n\n"
        "Generates:\n"
        "  • 3D tensor: 128×128×128 uint8 (binary voxel occupancy)\n"
        "  • 2D tensor: 128×128×3 uint8 (max projections: XY, XZ, YZ)\n"
        "  • PNG visualization: 2D stacked projections (local environment only)\n"
        "  • Interactive plots: 2D matplotlib or 3D plotly (if visualization flags enabled)\n\n"
        "Environment detection:\n"
        "  • LOCAL: /home/samuel/Work/Muography_Denoising/MuonGeneration/data/ground_truth_data/\n"
        "  • CLUSTER: /gpfs/projects/cms/dominguezs/data/ground_truth_data/"
    ),
    formatter_class=argparse.RawDescriptionHelpFormatter,
    epilog=(
        "JSON AUTO-RESOLUTION:\n"
        "  Just provide the filename, and the script will search the appropriate folder:\n"
        "  • LOCAL: /home/samuel/Work/Muography_Denoising/MuonGeneration/data/geometric_configurations_json\n"
        "  • CLUSTER: /gpfs/users/dominguezs/Muography_Denoising/MuonGeneration/data/geometric_configurations_json\n\n"
        "EXAMPLES:\n"
        "  # Basic usage (just the filename)\n"
        "  python3 create_ground_truth_from_json.py --json geometry.json\n\n"
        "  # Multiple files\n"
        "  python3 create_ground_truth_from_json.py --json geom1.json geom2.json geom3.json\n\n"
        "  # With visualization\n"
        "  python3 create_ground_truth_from_json.py --json geometry.json --visualize_2d\n"
        "  python3 create_ground_truth_from_json.py --json geometry.json --visualize_3d\n\n"
        "  # Custom world/voxel size with visualization\n"
        "  python3 create_ground_truth_from_json.py --json geometry.json --world_size 256 --voxel_size 2.0 --visualize_2d\n\n"
        "  # Verbose output\n"
        "  python3 create_ground_truth_from_json.py --json geometry.json --verbose"
    )
)

parser.add_argument("--json", type=str, nargs='+', required=True,
    help="JSON filename(s) in geometric_configurations_json folder (e.g., 'geometry.json'). Auto-searches in appropriate environment folder.")

parser.add_argument("--world_size", type=float, default=128.0,
    help="World size in cm (default: 128.0, maps to [-64, +64] in each axis)")

parser.add_argument("--voxel_size", type=float, default=1.0,
    help="Voxel size in cm (default: 1.0, determines tensor resolution)")

parser.add_argument("--visualize_2d", action="store_true", default=False,
    help="Display 2D projections (XY, XZ, YZ) in matplotlib window (loads from saved .npy file)")

parser.add_argument("--visualize_3d", action="store_true", default=False,
    help="Display 3D interactive visualization in browser with plotly (loads from saved .npy file)")

parser.add_argument("--verbose", action="store_true",
    help="Print detailed processing information")

args = parser.parse_args()

# Detect environment and get output paths
environment, output_3d_dir, output_2d_dir, json_base = detect_environment_and_paths()

print(f"[INFO] Environment detected: {environment}")
print(f"[INFO] JSON folder: {json_base}")
print(f"[INFO] 3D output directory: {output_3d_dir}")
print(f"[INFO] 2D output directory: {output_2d_dir}")

# Resolve JSON filenames to full paths
json_files = resolve_json_files(args.json, json_base)


# ===========================================================================
# SAVING FUNCTIONS (AUTOMATIC, NO VISUALIZATIONS IN CLUSTER)
# ===========================================================================

def save_2d_projections(tensor, output_path, world_size):
    """Save 3 orthogonal projections as stacked array (128×128×3)."""
    # Compute max projections
    projection_xy = np.max(tensor, axis=2)  # Top view (max over Z)
    projection_xz = np.max(tensor, axis=0)  # Front view (max over Y)
    projection_yz = np.max(tensor, axis=1)  # Side view (max over X)
    
    # Stack into single array: [y, x, projection_type]
    projections_stacked = np.stack([projection_xy, projection_xz, projection_yz], axis=2)
    
    np.save(output_path, projections_stacked)
    print(f"[CORRECT] 2D projections saved: {output_path}")
    print(f"          Shape: {projections_stacked.shape} (XY, XZ, YZ)")
    
    return projections_stacked


def save_3d_tensor(tensor, output_path):
    """Save 3D tensor directly."""
    np.save(output_path, tensor)
    print(f"[CORRECT] 3D tensor saved: {output_path}")
    print(f"          Shape: {tensor.shape}")


def visualize_2d_local(tensor, metadata, output_2d_dir, world_size):
    """Generate PNG visualization of 2D projections (local environment only)."""
    try:
        import matplotlib.pyplot as plt
        
        world_min = -world_size / 2.0
        world_max = +world_size / 2.0
        
        projection_xy = np.max(tensor, axis=2)
        projection_xz = np.max(tensor, axis=0)
        projection_yz = np.max(tensor, axis=1)
        
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        
        axes[0].imshow(projection_xy, origin='lower', cmap='gray',
                       extent=[world_min, world_max, world_min, world_max])
        axes[0].set_title('XY Projection (Top View)')
        axes[0].set_xlabel('X (cm)')
        axes[0].set_ylabel('Y (cm)')
        axes[0].grid(True, alpha=0.3)
        
        axes[1].imshow(projection_xz, origin='lower', cmap='gray',
                       extent=[world_min, world_max, world_min, world_max])
        axes[1].set_title('XZ Projection (Front View)')
        axes[1].set_xlabel('X (cm)')
        axes[1].set_ylabel('Z (cm)')
        axes[1].grid(True, alpha=0.3)
        
        axes[2].imshow(projection_yz, origin='lower', cmap='gray',
                       extent=[world_min, world_max, world_min, world_max])
        axes[2].set_title('YZ Projection (Side View)')
        axes[2].set_xlabel('Y (cm)')
        axes[2].set_ylabel('Z (cm)')
        axes[2].grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        png_path = output_2d_dir / f"visualization_2D_{metadata}.png"
        plt.savefig(png_path, dpi=150, bbox_inches='tight')
        print(f"[INFO] 2D visualization saved: {png_path}")
        plt.close()
    except ImportError:
        print("[WARNING] matplotlib not available for PNG visualization")


def visualize_2d_interactive(tensor_2d):
    """Display 2D projections interactively using matplotlib.
    
    Args:
        tensor_2d: 3D array with shape (128, 128, 3) containing XY, XZ, YZ projections
    """
    try:
        import matplotlib.pyplot as plt
        
        projection_xy = tensor_2d[:, :, 0]
        projection_xz = tensor_2d[:, :, 1]
        projection_yz = tensor_2d[:, :, 2]
        
        fig, axes = plt.subplots(1, 3, figsize=(16, 5))
        
        axes[0].imshow(projection_xy, origin='lower', cmap='hot')
        axes[0].set_title('XY Projection (Top View)', fontsize=12, fontweight='bold')
        axes[0].set_xlabel('X (index)')
        axes[0].set_ylabel('Y (index)')
        axes[0].grid(True, alpha=0.3)
        
        axes[1].imshow(projection_xz, origin='lower', cmap='hot')
        axes[1].set_title('XZ Projection (Front View)', fontsize=12, fontweight='bold')
        axes[1].set_xlabel('X (index)')
        axes[1].set_ylabel('Z (index)')
        axes[1].grid(True, alpha=0.3)
        
        axes[2].imshow(projection_yz, origin='lower', cmap='hot')
        axes[2].set_title('YZ Projection (Side View)', fontsize=12, fontweight='bold')
        axes[2].set_xlabel('Y (index)')
        axes[2].set_ylabel('Z (index)')
        axes[2].grid(True, alpha=0.3)
        
        plt.tight_layout()
        plt.show()
        
    except ImportError:
        print("[WARNING] matplotlib not available for visualization")


def visualize_3d_interactive(tensor_3d, world_size, voxel_size):
    """Display 3D geometry interactively using plotly with fixed voxel sizes.
    
    Args:
        tensor_3d: 3D array with shape (128, 128, 128) containing the geometry
        world_size: Size of the world in cm
        voxel_size: Size of each voxel in cm
    """
    try:
        import plotly.graph_objects as go
    except ImportError:
        print("[WARNING] plotly not installed. Install with: pip install plotly")
        return
    
    # Find all filled voxels
    filled_indices = np.argwhere(tensor_3d == 1)
    
    if len(filled_indices) == 0:
        print("[WARNING] No voxels to visualize")
        return
    
    world_min = -world_size / 2.0
    
    # Downsample for performance if needed
    if len(filled_indices) > 10000:
        # Keep every nth voxel for visualization
        stride = len(filled_indices) // 10000
        filled_indices = filled_indices[::stride]
        print(f"[INFO] Downsampled to {len(filled_indices)} voxels for visualization")
    
    # Convert indices to world coordinates (center of voxel)
    voxel_positions = filled_indices * voxel_size + world_min + voxel_size / 2.0
    
    x_coords = voxel_positions[:, 1]  # X is the 2nd index
    y_coords = voxel_positions[:, 0]  # Y is the 1st index
    z_coords = voxel_positions[:, 2]  # Z is the 3rd index
    
    # Create 3D scatter plot with FIXED voxel sizes
    # Use marker size that's independent of zoom level
    fig = go.Figure(data=[go.Scatter3d(
        x=x_coords,
        y=y_coords,
        z=z_coords,
        mode='markers',
        marker=dict(
            size=4,  # Fixed size in display coordinates
            color=z_coords,  # Color by Z coordinate
            colorscale='Viridis',
            showscale=True,
            colorbar=dict(title="Z (cm)"),
            opacity=0.8,
            line=dict(width=0)  # No edge lines to keep performance
        ),
        text=[f'Voxel: ({x:.1f}, {y:.1f}, {z:.1f}) cm' for x, y, z in 
              zip(x_coords, y_coords, z_coords)],
        hovertemplate='<b>%{text}</b><extra></extra>'
    )])
    
    # Set fixed aspect ratio and equal axis ranges for proportional display
    world_max = -world_min
    
    fig.update_layout(
        title=dict(
            text='3D Ground Truth Geometry (Fixed Voxel Proportions)',
            font=dict(size=16)
        ),
        scene=dict(
            xaxis=dict(
                title='X (cm)',
                range=[world_min, world_max],
                backgroundcolor="rgb(230, 230, 230)",
                gridcolor="white",
                showbackground=True,
                spikecolor="black"
            ),
            yaxis=dict(
                title='Y (cm)',
                range=[world_min, world_max],
                backgroundcolor="rgb(230, 230, 230)",
                gridcolor="white",
                showbackground=True,
                spikecolor="black"
            ),
            zaxis=dict(
                title='Z (cm)',
                range=[world_min, world_max],
                backgroundcolor="rgb(230, 230, 230)",
                gridcolor="white",
                showbackground=True,
                spikecolor="black"
            ),
            # CRITICAL: Set aspectratio to 1:1:1 for fixed voxel proportions
            aspectratio=dict(x=1, y=1, z=1),
            camera=dict(
                eye=dict(x=1.5, y=1.5, z=1.3)
            )
        ),
        width=1000,
        height=900,
        hovermode='closest',
        paper_bgcolor="white",
        plot_bgcolor="white"
    )
    
    print("[INFO] Opening 3D visualization in browser...")
    print("[INFO] You can rotate, zoom, and pan while maintaining fixed voxel proportions")
    fig.show()


# ===========================================================================
# INPUT VALIDATION
# ===========================================================================
print(f"\n[INFO] Processing {len(json_files)} geometry file(s)...")
print("=" * 70)

if args.voxel_size <= 0:
    sys.exit(f"[ERROR] voxel_size must be positive, got {args.voxel_size}")

if args.world_size <= 0:
    sys.exit(f"[ERROR] world_size must be positive, got {args.world_size}")


# ===========================================================================
# MAIN PROCESSING LOOP
# ===========================================================================
for json_idx, json_path in enumerate(json_files, 1):
    print(f"\n[{json_idx}/{len(json_files)}] Processing: {Path(json_path).name}")
    print("-" * 70)
    
    # Extract metadata from filename
    metadata = extract_metadata_from_json_filename(json_path)
    
    # Load JSON
    try:
        with open(json_path, 'r') as f:
            geometry = json.load(f)
    except json.JSONDecodeError as e:
        print(f"[ERROR] Failed to parse JSON: {e}")
        continue
    
    if "TheVoxels" not in geometry:
        print("[ERROR] JSON missing 'TheVoxels' key")
        continue
    
    voxels = geometry["TheVoxels"]
    print(f"[INFO] Found {len(voxels)} voxels in geometry")
    
    # Calculate tensor dimensions
    world_min = -args.world_size / 2.0
    world_max = +args.world_size / 2.0
    n_voxels = int(args.world_size / args.voxel_size)
    
    if args.verbose:
        print(f"[DEBUG] World bounds: [{world_min:.1f}, {world_max:.1f}] cm")
        print(f"[DEBUG] Tensor shape: {n_voxels}×{n_voxels}×{n_voxels}")
    
    # Create binary tensor
    tensor = np.zeros((n_voxels, n_voxels, n_voxels), dtype=np.uint8)
    filled_voxels = 0
    
    if args.verbose:
        print("[INFO] Processing voxels...")
    
    for i, voxel in enumerate(voxels):
        # Skip air voxels
        if voxel.get("materialVoxel", "air").lower() == "air":
            continue
        
        # Extract voxel position and size (in cm)
        x_center = voxel["xPosVoxel"]
        y_center = voxel["yPosVoxel"]
        z_center = voxel["zPosVoxel"]
        
        x_size = voxel["xSizeVoxel"]
        y_size = voxel["ySizeVoxel"]
        z_size = voxel["zSizeVoxel"]
        
        # Calculate voxel boundaries
        x_min = x_center - x_size / 2.0
        x_max = x_center + x_size / 2.0
        y_min = y_center - y_size / 2.0
        y_max = y_center + y_size / 2.0
        z_min = z_center - z_size / 2.0
        z_max = z_center + z_size / 2.0
        
        # Convert cm positions to tensor indices
        x_idx_min = int(np.floor((x_min - world_min) / args.voxel_size))
        x_idx_max = int(np.ceil((x_max - world_min) / args.voxel_size))
        y_idx_min = int(np.floor((y_min - world_min) / args.voxel_size))
        y_idx_max = int(np.ceil((y_max - world_min) / args.voxel_size))
        z_idx_min = int(np.floor((z_min - world_min) / args.voxel_size))
        z_idx_max = int(np.ceil((z_max - world_min) / args.voxel_size))
        
        # Clamp indices to tensor bounds
        x_idx_min = max(0, min(x_idx_min, n_voxels))
        x_idx_max = max(0, min(x_idx_max, n_voxels))
        y_idx_min = max(0, min(y_idx_min, n_voxels))
        y_idx_max = max(0, min(y_idx_max, n_voxels))
        z_idx_min = max(0, min(z_idx_min, n_voxels))
        z_idx_max = max(0, min(z_idx_max, n_voxels))
        
        # Mark tensor voxels
        tensor[y_idx_min:y_idx_max, x_idx_min:x_idx_max, z_idx_min:z_idx_max] = 1
        filled_voxels += 1
        
        if args.verbose and (i % 100 == 0):
            print(f"  [{i}/{len(voxels)}]")
    
    # Calculate statistics
    total_filled = int(np.sum(tensor))
    occupancy = 100.0 * total_filled / (n_voxels ** 3)
    
    print(f"[INFO] Statistics:")
    print(f"       Material voxels: {filled_voxels}")
    print(f"       Tensor voxels filled: {total_filled}")
    print(f"       Occupancy: {occupancy:.2f}%")
    
    # Generate output filenames
    tensor_3d_path = output_3d_dir / f"tensor_3D_{metadata}.npy"
    tensor_2d_path = output_2d_dir / f"tensor_2D_{metadata}.npy"
    
    # Save tensors
    save_3d_tensor(tensor, tensor_3d_path)
    save_2d_projections(tensor, tensor_2d_path, args.world_size)
    
    # Generate PNG visualization in local environment
    if environment == "local":
        visualize_2d_local(tensor, metadata, output_2d_dir, args.world_size)
    
    # Interactive visualizations (if flags are enabled)
    # Load from saved .npy files to visualize exactly what was saved
    if args.visualize_2d:
        print("\n[INFO] Loading saved 2D tensor and displaying...")
        tensor_2d_loaded = np.load(tensor_2d_path)
        visualize_2d_interactive(tensor_2d_loaded)
    
    if args.visualize_3d:
        print("\n[INFO] Loading saved 3D tensor and displaying...")
        tensor_3d_loaded = np.load(tensor_3d_path)
        visualize_3d_interactive(tensor_3d_loaded, args.world_size, args.voxel_size)
    
    print("[OK] Processing complete for this file")

print("\n" + "=" * 70)
print("[SUCCESS] All geometries processed!")
