"""
Create ground truth binary geometry tensors from Geant4 JSON configuration files.

DESCRIPTION:
    Reads a JSON geometry file (generated by create_geometry.py) and converts it to a 
    3D binary numpy tensor at a specified resolution. Each voxel in the JSON is 
    discretized into smaller voxels, creating a volumetric ground truth representation.

INPUT:
    JSON file with structure:
    {
        "theWorld": { "xSizeWorld": float, ... },
        "TheVoxels": [
            {
                "xPosVoxel": float (cm),
                "yPosVoxel": float (cm),
                "zPosVoxel": float (cm),
                "xSizeVoxel": float (cm),
                "ySizeVoxel": float (cm),
                "zSizeVoxel": float (cm),
                "materialVoxel": str (e.g., "lead", "air")
            },
            ...
        ]
    }

OUTPUT:
    3D numpy binary tensor (128×128×128 by default)
    - Value 1: voxel occupied (material present)
    - Value 0: empty (air)

USAGE:
    # Default: read JSON, save 128×128×128 tensor
    python3 create_ground_truth_from_json.py --json geometry.json --output ground_truth.npy
    
    # Custom resolution (512×512×512 with 0.25cm voxels)
    python3 create_ground_truth_from_json.py --json geometry.json --output gt.npy \\
            --world_size 128 --voxel_size 0.25
    
    # Custom world bounds (-80 to +80 cm in each dimension)
    python3 create_ground_truth_from_json.py --json geometry.json \\
            --world_min -80 --world_max 80 --voxel_size 1.25
"""

import json
import argparse
import numpy as np
import sys
from pathlib import Path

# ===========================================================================
# ARGUMENT PARSING
# ===========================================================================
parser = argparse.ArgumentParser(description="Convert JSON geometry to binary 3D tensor")

parser.add_argument("--json", type=str, required=True,
    help="Path to Geant4 JSON geometry file")

parser.add_argument("--output", type=str, required=True,
    help="Path for output numpy tensor (.npy file)")

parser.add_argument("--world_size", type=float, default=128.0,
    help="Total world size in cm (world goes from -world_size/2 to +world_size/2). Default: 128.0")

parser.add_argument("--voxel_size", type=float, default=1.0,
    help="Size of each voxel in cm (1.0 = 1cm × 1cm × 1cm). Default: 1.0")

parser.add_argument("--visualize_2d", action="store_true",
    help="Generate 2D visualizations of the three orthogonal projections (XY, XZ, YZ)")

parser.add_argument("--visualize_3d", action="store_true",
    help="Generate 3D interactive HTML visualization of the geometry")

parser.add_argument("--verbose", action="store_true",
    help="Print detailed information during processing")

parser.add_argument("--environment", type=str, choices=["local", "cluster"], default="local",
    help="Execution environment: 'local' generates graphics (PNG, HTML), 'cluster' disables graphics. Default: local")

args = parser.parse_args()


# ===========================================================================
# VISUALIZATION FUNCTIONS
# ===========================================================================

def visualize_2d(tensor, output_path, world_size):
    """Generate 2D matplotlib visualization of three orthogonal projections."""
    import matplotlib.pyplot as plt
    
    # Calculate world bounds
    world_min = -world_size / 2.0
    world_max = +world_size / 2.0
    
    # Compute max projections (binary)
    projection_xy = np.max(tensor, axis=2)  # Top view (max over Z)
    projection_xz = np.max(tensor, axis=0)  # Front view (max over Y)
    projection_yz = np.max(tensor, axis=1)  # Side view (max over X)
    
    # Create figure with three subplots
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # XY projection (top view)
    axes[0].imshow(projection_xy, origin='lower', cmap='gray', 
                   extent=[world_min, world_max, world_min, world_max])
    axes[0].set_title('XY Projection (Top View)')
    axes[0].set_xlabel('X (cm)')
    axes[0].set_ylabel('Y (cm)')
    axes[0].grid(True, alpha=0.3)
    
    # XZ projection (front view)
    axes[1].imshow(projection_xz, origin='lower', cmap='gray',
                   extent=[world_min, world_max, world_min, world_max])
    axes[1].set_title('XZ Projection (Front View)')
    axes[1].set_xlabel('X (cm)')
    axes[1].set_ylabel('Z (cm)')
    axes[1].grid(True, alpha=0.3)
    
    # YZ projection (side view)
    axes[2].imshow(projection_yz, origin='lower', cmap='gray',
                   extent=[world_min, world_max, world_min, world_max])
    axes[2].set_title('YZ Projection (Side View)')
    axes[2].set_xlabel('Y (cm)')
    axes[2].set_ylabel('Z (cm)')
    axes[2].grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    # Save to file
    output_png = output_path.replace('.npy', '_projections_2D.png')
    plt.savefig(output_png, dpi=150, bbox_inches='tight')
    print(f"[CORRECT] 2D visualization saved: {output_png}")
    plt.close()


def visualize_3d(tensor, output_path, world_size, voxel_size):
    """Generate 3D interactive HTML visualization using plotly."""
    try:
        import plotly.graph_objects as go
    except ImportError:
        print("[WARNING] plotly not installed. Skipping 3D visualization.")
        print("          Install with: pip install plotly")
        return
    
    # Calculate voxel positions
    n_voxels = tensor.shape[0]
    world_min = -world_size / 2.0
    
    # Find all filled voxels
    filled_indices = np.argwhere(tensor == 1)
    
    if len(filled_indices) > 5000:
        # Downsample for performance if too many voxels
        sample_ratio = len(filled_indices) // 5000
        filled_indices = filled_indices[::sample_ratio]
        print(f"[INFO] Downsampled to {len(filled_indices)} voxels for visualization")
    
    # Convert indices to world coordinates
    voxel_positions = filled_indices * voxel_size + world_min + voxel_size / 2.0
    x_coords = voxel_positions[:, 1]  # X is the 2nd index
    y_coords = voxel_positions[:, 0]  # Y is the 1st index
    z_coords = voxel_positions[:, 2]  # Z is the 3rd index
    
    # Create 3D scatter plot
    fig = go.Figure(data=[go.Scatter3d(
        x=x_coords,
        y=y_coords,
        z=z_coords,
        mode='markers',
        marker=dict(
            size=2,
            color='blue',
            opacity=0.6,
            showscale=False
        ),
        text=[f'Voxel at ({x:.1f}, {y:.1f}, {z:.1f})' for x, y, z in 
              zip(x_coords, y_coords, z_coords)],
        hoverinfo='text'
    )])
    
    fig.update_layout(
        title='3D Geometry Visualization (Ground Truth)',
        scene=dict(
            xaxis_title='X (cm)',
            yaxis_title='Y (cm)',
            zaxis_title='Z (cm)',
            xaxis=dict(range=[world_min, -world_min]),
            yaxis=dict(range=[world_min, -world_min]),
            zaxis=dict(range=[world_min, -world_min]),
        ),
        width=900,
        height=900,
        hovermode='closest'
    )
    
    # Save to HTML
    output_html = output_path.replace('.npy', '_visualization_3D.html')
    fig.write_html(output_html)
    print(f"[CORRECT] 3D visualization saved: {output_html}")
    print(f"          Open in browser to interact (rotate, zoom, pan)")


# ===========================================================================
# INPUT VALIDATION
# ===========================================================================
if not Path(args.json).exists():
    sys.exit(f"[ERROR] JSON file not found: {args.json}")

if args.voxel_size <= 0:
    sys.exit(f"[ERROR] voxel_size must be positive, got {args.voxel_size}")

if args.world_size <= 0:
    sys.exit(f"[ERROR] world_size must be positive, got {args.world_size}")

# Create output directory if needed
output_dir = Path(args.output).parent
output_dir.mkdir(parents=True, exist_ok=True)


# ===========================================================================
# LOAD JSON GEOMETRY
# ===========================================================================
print("[INFO] Loading JSON geometry file...")
try:
    with open(args.json, 'r') as f:
        geometry = json.load(f)
except json.JSONDecodeError as e:
    sys.exit(f"[ERROR] Failed to parse JSON: {e}")

if "TheVoxels" not in geometry:
    sys.exit("[ERROR] JSON missing 'TheVoxels' key")

voxels = geometry["TheVoxels"]
print(f"[INFO] Found {len(voxels)} voxels in geometry")


# ===========================================================================
# CALCULATE TENSOR DIMENSIONS
# ===========================================================================
world_min = -args.world_size / 2.0
world_max = +args.world_size / 2.0
n_voxels = int(args.world_size / args.voxel_size)

print(f"[INFO] World bounds: [{world_min:.1f}, {world_max:.1f}] cm in each dimension")
print(f"[INFO] Voxel size: {args.voxel_size} cm")
print(f"[INFO] Tensor shape: {n_voxels}×{n_voxels}×{n_voxels}")


# ===========================================================================
# CREATE BINARY TENSOR
# ===========================================================================
# Initialize empty tensor (0 = empty, 1 = filled)
tensor = np.zeros((n_voxels, n_voxels, n_voxels), dtype=np.uint8)

print("[INFO] Processing voxels...")
filled_voxels = 0

for i, voxel in enumerate(voxels):
    # Skip air voxels (we only care about material)
    if voxel.get("materialVoxel", "air").lower() == "air":
        continue
    
    # Extract voxel position and size (all in cm)
    x_center = voxel["xPosVoxel"]
    y_center = voxel["yPosVoxel"]
    z_center = voxel["zPosVoxel"]
    
    x_size = voxel["xSizeVoxel"]
    y_size = voxel["ySizeVoxel"]
    z_size = voxel["zSizeVoxel"]
    
    # Calculate voxel boundaries
    x_min = x_center - x_size / 2.0
    x_max = x_center + x_size / 2.0
    y_min = y_center - y_size / 2.0
    y_max = y_center + y_size / 2.0
    z_min = z_center - z_size / 2.0
    z_max = z_center + z_size / 2.0
    
    # Convert cm positions to tensor indices
    # Index 0 corresponds to world_min, index n_voxels-1 to world_max
    x_idx_min = int(np.floor((x_min - world_min) / args.voxel_size))
    x_idx_max = int(np.ceil((x_max - world_min) / args.voxel_size))
    y_idx_min = int(np.floor((y_min - world_min) / args.voxel_size))
    y_idx_max = int(np.ceil((y_max - world_min) / args.voxel_size))
    z_idx_min = int(np.floor((z_min - world_min) / args.voxel_size))
    z_idx_max = int(np.ceil((z_max - world_min) / args.voxel_size))
    
    # Clamp indices to tensor bounds
    x_idx_min = max(0, min(x_idx_min, n_voxels))
    x_idx_max = max(0, min(x_idx_max, n_voxels))
    y_idx_min = max(0, min(y_idx_min, n_voxels))
    y_idx_max = max(0, min(y_idx_max, n_voxels))
    z_idx_min = max(0, min(z_idx_min, n_voxels))
    z_idx_max = max(0, min(z_idx_max, n_voxels))
    
    # Mark all tensor voxels occupied by this geometry voxel
    # Indexing: [y, x, z] to match typical array conventions (row=y, col=x, depth=z)
    tensor[y_idx_min:y_idx_max, x_idx_min:x_idx_max, z_idx_min:z_idx_max] = 1
    filled_voxels += 1
    
    if args.verbose and (i % 50 == 0):
        print(f"  Processed {i}/{len(voxels)} voxels...")


# ===========================================================================
# SAVE TENSOR
# ===========================================================================
total_filled = int(np.sum(tensor))
occupancy = 100.0 * total_filled / (n_voxels ** 3)

np.save(args.output, tensor)
print(f"[CORRECT] Ground truth tensor saved: {args.output}")
print(f"[INFO] Statistics:")
print(f"       Material voxels in JSON: {filled_voxels}")
print(f"       Filled voxels in tensor: {total_filled}")
print(f"       Occupancy: {occupancy:.2f}%")
print(f"       Tensor shape: {tensor.shape}")
print(f"       Data type: {tensor.dtype}")


# ===========================================================================
# VISUALIZATION (OPTIONAL - LOCAL ENVIRONMENT ONLY)
# ===========================================================================
if args.environment == "local":
    if args.visualize_2d:
        print("\n[INFO] Generating 2D projections...")
        visualize_2d(tensor, args.output, args.world_size)
    
    if args.visualize_3d:
        print("\n[INFO] Generating 3D interactive visualization...")
        visualize_3d(tensor, args.output, args.world_size, args.voxel_size)
else:
    if args.visualize_2d or args.visualize_3d:
        print("\n[INFO] Visualization disabled in 'cluster' environment (no GUI available)")
