"""
================================================================================
create_h5_dataset1.py

Converts MERGED_*.npy (POCA1 reconstructions with 4 channels) + ground_truth
density into HDF5 datasets for UNET1_2D training.

UNET1_2D uses 4-channel input with enhanced geometry reconstruction:
  - Channel 0: log_counts (event density)
  - Channel 1: mean_theta_sq_z (scattering angle)
  - Channel 2: var_poca_z (Z-coordinate variance → thickness proxy)
  - Channel 3: std_theta (scattering variance → material discrimination)

================================================================================
QUICK START
================================================================================

STEP 1: Prerequisites
  ✓ Run loop_configuration_files.py first to generate MERGED_*.npy files
  ✓ Ensure ground_truth_density2D.npy exists for each geometry
  ✓ Configure paths below (ENVIRONMENT setting)

STEP 2: Run the script
  
  LOCAL MODE (for testing):
    cd /home/samuel/Work/Muography_Denoising/MuonGeneration/UNETs
    python3 create_h5_dataset1.py
  
  CLUSTER MODE:
    cd /gpfs/users/dominguezs/Muography_Denoising/MuonGeneration/UNETs
    python3 create_h5_dataset1.py
  
  Or via SLURM job (recommended for large datasets):
    sbatch -J h5_creation --time=02:00:00 --mem=32G --cpus-per-task=4 \\
           --wrap="python3 create_h5_dataset1.py"

STEP 3: Use the generated H5 files for training
  
  Example TensorFlow code:
    import h5py
    import tensorflow as tf
    
    h5_path = "data/h5_datasets/128x128x4.h5"  # 4-channel input for UNET1_2D
    
    with h5py.File(h5_path, 'r') as f:
        train_images = f['training/images'][:]
        train_labels = f['training/labels'][:]
        print(f"Train images shape: {train_images.shape}")
        print(f"Noise variability (muons): {f.attrs['n_muons_min']:,} - {f.attrs['n_muons_max']:,}")
        print(f"Training on mixed-noise data? {f.attrs['has_mixed_muon_counts']}")
    
    # Build your dataset (will include variable-noise samples)
    train_dataset = tf.data.Dataset.from_tensor_slices(
        (train_images, train_labels)
    ).batch(32).shuffle(1000)
    
    # TIP: Model trains on data with different noise levels (different n_muons_total)
    # This makes it robust to simulation variability

================================================================================
CONFIGURATION & CUSTOMIZATION
================================================================================

Modify these variables at the top of the script to control behavior:

  ENVIRONMENT = "cluster"  # "local" or "cluster"
                           # Controls which paths are used
  
  TRAIN_RATIO = 0.70       # Fraction of data for training (default 70%)
  VAL_RATIO = 0.15         # Validation set fraction (default 15%)
  TEST_RATIO = 0.15        # Test set fraction (default 15%)
                           # Sum should equal 1.0
  
  COMPRESSION = 'gzip'     # 'gzip' or 'lzf'
  COMPRESSION_OPTS = 4     # 0 (none) to 9 (max)
                           # 4 = good balance between compression & speed
  
  RANDOM_SEED = 42         # Seed for reproducible train/val/test splits
  
  TOTAL_MUONS_PER_SIMULATION = 1_000_000
                           # Muon count used in simulations
                           # CRITICAL: Update if you run simulations with different counts
                           # Higher muon count → lower noise → better training data

================================================================================
INPUT DATA REQUIREMENTS
================================================================================

This script expects:

1. MERGED_*.npy files in merged_poca_data/ directory
   - Generated by merge_results_1.py (UNET1 variant)
   - Filename format: MERGED_<geometry_params>_Muons_<count>_2D.npy
   - Each file is a numpy dict with key:
     • "training_channels": (H, W, 4) - 4-channel POCA reconstruction
       * Channel 0: log_counts (event density)
       * Channel 1: mean_theta_sq_z (scattering angle)
       * Channel 2: var_poca_z (Z-variance, thickness proxy)
       * Channel 3: std_theta (scattering variance, material discrimination)

2. Ground truth density files in ground_truth_data/2Dimensions/
   - Filename format: <geometry_name>_ground_truth_density2D.npy
   - Shape: (H, W) or (H, W, 1)
   - Values: normalized density (0-1 or raw counts)

3. Geometry hyperparameters encoded in filename:
   _Lpx<val>_Lpy<val>_Lpz<val>_npx<val>_npy<val>_npz<val>
   _zTop<val>_zBot<val>_spacing<val>_ratio<val>
   _FontX<val>_FontY<val>_mat<type>_word<word>_stroke<val>

================================================================================
OUTPUT STRUCTURE
================================================================================

The script creates H5 files in data/h5_datasets/ directory, **ONE PER RESOLUTION**:

  128x128x4.h5       (All 128x128 4-channel POCA images for UNET1_2D)
  256x256x4.h5       (If supported in future)
  ...

KEY DESIGN: Different noise levels (muon counts) are **mixed in same H5**.
- Each sample has n_muons_total in its metadata
- Model trains on variable-noise data → learns robust denoiser
- File-level attrs show min/max/avg muons for reference

Each H5 file internal structure:

  /training/
    ├── images       (N_train, H, W, 4) float32
    │                4 POCA channels: [log_counts, mean_theta_sq_z, var_poca_z, std_theta]
    ├── labels       (N_train, H, W, 1) float32
    │                Ground truth density
    └── metadata/
        ├── sample_000000/ (attributes: Lpx, Lpy, npx, npy, material, n_muons_total, ...)
        ├── sample_000001/
        └── ...
  /validation/
    ├── images, labels, metadata/ (same structure)
  /test/
    ├── images, labels, metadata/ (same structure)
  geometry_names (dataset with geometry names as UTF-8 strings)

FILE ATTRIBUTES (accessible with h5file.attrs):
  • resolution                : String like "128x128x4_Muons_1000000"
  • total_samples             : Total number of samples in this H5
  • train_ratio, val_ratio, test_ratio : Split fractions
  • compression, compression_opts : HDF5 compression settings
  • random_seed               : Seed used for train/val/test splits
  • n_muons_min               : Minimum muon count in this H5 (dataset variability)
  • n_muons_max               : Maximum muon count in this H5
  • n_muons_avg               : Average muon count (good for reference)
  • has_mixed_muon_counts     : Boolean, True if multiple muon counts present
                               (indicates trained on variable-noise data)

SAMPLE-LEVEL METADATA (per training instance):
  Each sample in /training/metadata/sample_XXXXXX/ has attributes:
  • n_muons_total             : **CRITICAL** - exact muon count for THIS sample (affects noise)
  • Lpx, Lpy, Lpz             : Physical box dimensions
  • npx, npy, npz             : Grid resolution
  • material                  : Material type (lead, iron, uranium)
  • word                      : Geometry type (MUON, MUNO, etc)
  • stroke                    : Stroke width
  • zTop, zBot                : Detector positions
  • FontX, FontY              : Font/text size parameters
  • spacing, ratio            : Detector spacing and scattering ratio

================================================================================
HOW TO USE THE GENERATED H5 FILES
================================================================================

OPTION 1: Load entire dataset into memory (fast, for small datasets)
  
  import h5py
  import numpy as np
  
  h5_path = "data/h5_datasets/128x128x4.h5"
  
  with h5py.File(h5_path, 'r') as f:
      train_images = f['training/images'][:]       # Shape: (N, 128, 128, 4)
      train_labels = f['training/labels'][:]       # Shape: (N, 128, 128, 1)
      val_images = f['validation/images'][:]
      val_labels = f['validation/labels'][:]
  
  print(f"Training: {train_images.shape}")
  print(f"Muons per sim: {f.attrs['n_muons_per_simulation']}")

OPTION 2: Lazy loading with TensorFlow (recommended for large datasets)
  
  import h5py
  import tensorflow as tf
  
  def load_from_h5(h5_path, split='training', batch_size=32):
      with h5py.File(h5_path, 'r') as f:
          images = f[f'{split}/images'][:]
          labels = f[f'{split}/labels'][:]
      
      dataset = tf.data.Dataset.from_tensor_slices((images, labels))
      dataset = dataset.shuffle(buffer_size=1000)
      dataset = dataset.batch(batch_size)
      dataset = dataset.prefetch(tf.data.AUTOTUNE)
      
      return dataset
  
  train_ds = load_from_h5('128x128x4.h5', 'training', batch_size=32)

OPTION 3: Access sample metadata (IMPORTANT for understanding training data)
  
  with h5py.File(h5_path, 'r') as f:
      # Get metadata for first training sample
      sample_attrs = f['training/metadata/sample_000000'].attrs
      
      print(f"Sample info:")
      print(f"  Muons: {sample_attrs['n_muons_total']}")
      print(f"  Material: {sample_attrs['material']}")
      print(f"  Geometry: {sample_attrs['word']}")
      print(f"  Grid: {sample_attrs['npx']} x {sample_attrs['npy']}")
      
      # Iterate over multiple samples to see noise variation
      for i in range(min(10, f['training/metadata'].attrs.get('n_samples', 0))):
          attrs = f[f'training/metadata/sample_{i:06d}'].attrs
          print(f"Sample {i}: {attrs['n_muons_total']:,} muons - {attrs['word']}")

OPTION 3b: Analyze muon count distribution in dataset
  
  with h5py.File(h5_path, 'r') as f:
      # Get file-level statistics
      print(f"Muon count statistics for {f.attrs['resolution']}:")
      print(f"  Min: {f.attrs['n_muons_min']:,} muons")
      print(f"  Max: {f.attrs['n_muons_max']:,} muons")
      print(f"  Avg: {f.attrs['n_muons_avg']:,} muons")
      print(f"  Mixed noise levels? {f.attrs['has_mixed_muon_counts']}")
      
      # Why this matters: If has_mixed_muon_counts=True, the model trains
      # on variable-noise data and becomes robust to different simulation runs

OPTION 4: Append new data to existing H5 (for incremental training)
  
  import h5py
  import numpy as np
  
  h5_path = "128x128x4.h5"
  
  with h5py.File(h5_path, 'a') as f:
      # Get current size
      n_current = f['training/images'].shape[0]
      
      # Resize to add space for new samples
      n_new = 10  # 10 new training samples
      f['training/images'].resize(n_current + n_new, axis=0)
      f['training/labels'].resize(n_current + n_new, axis=0)
      
      # Add new data
      f['training/images'][n_current:] = new_images  # Shape: (10, 128, 128, 4)
      f['training/labels'][n_current:] = new_labels  # Shape: (10, 128, 128, 1)

================================================================================
WORKFLOW DIAGRAM
================================================================================

loop_configuration_files1.py (creates MERGED_*.npy, ground truth)
         ↓
POCA1.py & merge_results_1.py (4-channel reconstruction)
         ↓
create_h5_dataset1.py (THIS SCRIPT)
         ↓
H5 datasets (128x128x4.h5) organized by resolution + muon count
         ↓
TensorFlow UNET training (UNET1_2D.py)

================================================================================
GEOMETRIC HYPERPARAMETERS (extracted from filename)
================================================================================

All these parameters are automatically extracted and stored in metadata:

  _Lpx{value}        : X dimension of physical box (cm)
  _Lpy{value}        : Y dimension of physical box (cm)
  _Lpz{value}        : Z dimension of physical box (cm)
  _npx{value}        : Grid points X
  _npy{value}        : Grid points Y
  _npz{value}        : Grid points Z
  _zTop{value}       : Top detector position Z (cm)
  _zBot{value}       : Bottom detector position Z (cm)
  _spacing{value}    : Detector spacing (cm)
  _ratio{value}      : Scattering ratio parameter
  _FontX{value}      : Font size X (pixels)
  _FontY{value}      : Font size Y (pixels)
  _mat{material}     : Material type (iron, lead, concrete, etc)
  _word{word}        : Word/geometry type (MUON, MUNO, TEXT, etc)
  _stroke{value}     : Stroke width (pixels)
  _Muons_{count}     : Number of muons in simulation (NEW! affects noise level)

CRITICAL FOR TRAINING: n_muons_total
  • Stored per-sample in metadata
  • Stored file-wide in H5 attributes
  • IMPORTANT: Different muon counts = different noise levels
  • More muons → better statistics → lower noise
  • Can use this to weight samples or train robust to noise variations

================================================================================
TROUBLESHOOTING
================================================================================

Problem: "No MERGED files found"
  ✓ Did you run loop_configuration_files.py? Check PATH_MERGED directory exists
  ✓ Check file naming: should be MERGED_<geometry>_Muons_<count>2D.npy
  ✓ Ensure files completed successfully (check logs/ directory)

Problem: "Ground truth not found"
  ✓ Check PATH_GT_2D directory contains *_ground_truth_density2D.npy files
  ✓ Geometry name must match exactly between MERGED and GT files
  ✓ Look for "[SKIP] Ground truth not found" warnings

Problem: "Shape mismatch"
  ✓ Ensure POCA image resolution matches ground truth resolution
  ✓ Check that ground truth is 2D (not 3D)
  ✓ Validate MERGED file was created successfully (not corrupted)

Problem: H5 files too large
  ✓ Reduce COMPRESSION_OPTS (use 1 instead of 4)
  ✓ Split into multiple H5 files by geometry subset
  ✓ Remove metadata groups (not needed for training)

Problem: "Out of memory"
  ✓ Reduce batch size when loading
  ✓ Use lazy loading (Option 2 above) instead of loading all into memory
  ✓ Run on cluster node instead of login node

================================================================================
PERFORMANCE TIPS
================================================================================

• Run on cluster with sufficient memory (16GB+ recommended for 1000+ samples)
• Use --mem=32G and --cpus-per-task=4 when submitting as SLURM job
• COMPRESSION_OPTS=4 is optimal for cluster I/O operations
• Lazy loading with TensorFlow is faster than loading entire dataset
• Separate H5 files per resolution speeds up model training (load only what needed)

================================================================================
SIMULATION METADATA (critical for understanding training data robustness)
================================================================================

  n_muons_total      : Per-sample metadata storing exact muon count in THIS simulation
                       IMPORTANT: Different samples in same H5 may have different values
                       Higher n_muons → lower noise → different training difficulty
                       
  File-level stats:  n_muons_min, n_muons_max, n_muons_avg, has_mixed_muon_counts
                     These show the noise VARIABILITY in your dataset
                     Mixed counts = model trains on variable-noise data = more robust

DESIGN RATIONALE:
  By mixing different muon counts in same H5:
  ✓ Model sees variable noise levels during training
  ✓ Becomes robust to different simulation parameters
  ✓ Each sample is fully traceable (knows its exact muon count)
  ✓ Can analyze correlation between n_muons and model performance
  
  Example use case:
    - Train on mixed data (500k-1M muons per sample)
    - Test on 1M muons exclusively
    - Evaluate if variable-noise training improves generalization

================================================================================
"""

import numpy as np
import h5py
import os
import glob
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple
import re


# ==============================================================================
# CONFIGURATION
# ==============================================================================
# 
# ENVIRONMENT: Choose where the script runs
#   "cluster" : IFCA cluster paths (GPU nodes)
#   "local"   : Your local workstation
#
# Paths are automatically set based on ENVIRONMENT value below.
# Modify PATH_* variables directly if using custom directories.
#

ENVIRONMENT = "local"  # Options: "cluster" | "local"

if ENVIRONMENT == "cluster":
    PATH_MERGED = "/gpfs/users/dominguezs/Muography_Denoising/MuonGeneration/data/merged_poca_data"
    PATH_GT_2D = "/gpfs/users/dominguezs/Muography_Denoising/MuonGeneration/data/ground_truth_data/2Dimensions"
    PATH_OUTPUT = "/gpfs/users/dominguezs/Muography_Denoising/MuonGeneration/data/h5_datasets"

elif ENVIRONMENT == "local":
    PATH_MERGED = "/home/samuel/Work/Muography_Denoising/MuonGeneration/data/merged_poca_data"
    PATH_GT_2D = "/home/samuel/Work/Muography_Denoising/MuonGeneration/data/ground_truth_data/2Dimensions"
    PATH_OUTPUT = "/home/samuel/Work/Muography_Denoising/MuonGeneration/data/h5_datasets"





# Dataset split ratios
TRAIN_RATIO = 0.70
VAL_RATIO = 0.15
TEST_RATIO = 0.15

# HDF5 compression parameters
COMPRESSION = 'gzip'
COMPRESSION_OPTS = 4  # 0-9: 4 is good balance between compression & speed

# Random seed for reproducibility
RANDOM_SEED = 42

# === CRITICAL SIMULATION PARAMETER ===
# Total number of muons used in ALL simulations
# This is a critical metadata: directly affects noise level (more muons → less noise)
# IMPORTANT: Update this value when running simulations with different muon counts!
TOTAL_MUONS_PER_SIMULATION = 1_000_000  # 1 million muons per geometry


# ==============================================================================
# HELPER FUNCTIONS
# ==============================================================================
# These functions handle:
#   1. Parsing geometry parameters from filenames
#   2. Extracting POCA reconstruction channels
#   3. Loading and validating sample data
#   4. Organizing data into HDF5 format
#
# Key insight: All geometry parameters are encoded in the filename, making
# data provenance automatic and reproducible.
# ==============================================================================

def parse_geometric_hyperparameters(filename: str) -> Dict[str, any]:
    """
    Extract geometric hyperparameters from filename.
    
    Filename format:
      _Lpx{Lpx}_Lpy{Lpy}_Lpz{Lpz}_npx{npx}_npy{npy}_npz{npz}_zTop{zTop}_zBot{zBot}
      _spacing{spacing}_ratio{ratio}_FontX{FontX}_FontY{FontY}
      _mat{material}_word{word}_stroke{stroke}
    
    Args:
        filename: base filename (without extension)
    
    Returns:
        Dictionary with extracted parameters
    """
    params = {}
    
    # Define pattern for each parameter
    patterns = {
        'Lpx': r'_Lpx(\d+)',
        'Lpy': r'_Lpy(\d+)',
        'Lpz': r'_Lpz(\d+)',
        'npx': r'_npx(\d+)',
        'npy': r'_npy(\d+)',
        'npz': r'_npz(\d+)',
        'zTop': r'_zTop(-?\d+)',
        'zBot': r'_zBot(-?\d+)',
        'spacing': r'_spacing(\d+)',
        'ratio': r'_ratio(\d+)',
        'FontX': r'_FontX(\d+)',
        'FontY': r'_FontY(\d+)',
        'material': r'_mat(\w+)',
        'word': r'_word(\w+)',
        'stroke': r'_stroke(\d+)',
        'n_muons': r'_Muons_(\d+(?:_\d+)*)',
    }
    
    for key, pattern in patterns.items():
        match = re.search(pattern, filename)
        if match:
            value = match.group(1)
            # Convert numeric values to int, keep strings as-is
            try:
                # Remove underscores from numeric strings (e.g., "1_000_000" -> "1000000")
                clean_value = value.replace('_', '')
                params[key] = int(clean_value)
            except ValueError:
                params[key] = value
        else:
            # Only warn for critical parameters
            if key in ['npx', 'npy', 'n_muons']:
                print(f"[WARNING] Could not extract '{key}' from: {filename}")
    
    return params


def get_poca_channels(poca_dict: dict) -> np.ndarray:
    """
    Extract 4 POCA channels from merged data dictionary (UNET1_2D format).
    
    Channels:
      0: log_counts           - Logarithmic muon counts (event density)
      1: mean_theta_sq_z      - Mean squared scattering angle
      2: var_poca_z           - Z-coordinate variance (thickness proxy)
      3: std_theta            - Scattering angle standard deviation
    
    Args:
        poca_dict: Dictionary from MERGED_*.npy (loaded with allow_pickle=True)
                   Must contain 'training_channels' key with shape (H, W, 4)
    
    Returns:
        Array of shape (H, W, 4) with dtype float32
    """
    # Extract pre-computed 4-channel tensor from merge_results_1.py
    if "training_channels" in poca_dict:
        channels = poca_dict["training_channels"].astype(np.float32)
    else:
        raise KeyError("'training_channels' key not found. Ensure merge_results_1.py was used.")
    
    # Validate shape
    if channels.ndim != 3 or channels.shape[2] != 4:
        raise ValueError(f"Expected shape (H, W, 4), got {channels.shape}")
    
    return channels


def load_sample_pair(merged_path: str, gt_file_path: str, geom_name: str) -> Tuple[np.ndarray, np.ndarray, bool]:
    """
    Load POCA image and ground truth label pair.
    
    Args:
        merged_path: Full path to MERGED_*.npy file (4-channel from merge_results_1.py)
        gt_file_path: Full path to ground_truth_density2D.npy file
        geom_name: Geometry name (for error messages)
    
    Returns:
        (image, label, success) tuple
        - image: (H, W, 4) float32 4-channel POCA reconstruction
        - label: (H, W, 1) float32 ground truth density
        - success: bool indicating if loading succeeded
    """
    try:
        # Load POCA (4 channels from merge_results_1.py)
        poca_data = np.load(merged_path, allow_pickle=True).item()
        image = get_poca_channels(poca_data)
        
        # Load ground truth (already verified to exist)
        if not os.path.exists(gt_file_path):
            print(f"  [SKIP] GT file missing: {os.path.basename(gt_file_path)}")
            return None, None, False
        
        label = np.load(str(gt_file_path), allow_pickle=True).astype(np.float32)
        
        # Ensure label is (H, W, 1)
        if label.ndim == 2:
            label = label[:, :, np.newaxis]
        elif label.ndim != 3 or label.shape[2] != 1:
            print(f"  [SKIP] Label shape invalid: {label.shape}")
            return None, None, False
        
        # Validate shapes match
        if image.shape[:2] != label.shape[:2]:
            print(f"  [SKIP] Shape mismatch: image {image.shape} vs label {label.shape}")
            return None, None, False
        
        return image, label, True
    
    except Exception as e:
        print(f"  [ERROR] {str(e)}")
        return None, None, False


def create_flexible_h5_split(h5_file: h5py.File, split_name: str, 
                             images: List[np.ndarray], labels: List[np.ndarray], 
                             hyperparams: List[Dict]) -> int:
    """
    Create HDF5 groups for a dataset split (train/val/test).
    Uses chunking to allow appending new data later.
    
    Args:
        h5_file: Open HDF5 file
        split_name: Split name ("training", "validation", "test")
        images: List of image arrays (H, W, 4) - 4-channel POCA reconstruction
        labels: List of label arrays (H, W, 1) - ground truth density
        hyperparams: List of hyperparameter dicts
    
    Returns:
        Number of samples added
    """
    if len(images) == 0:
        print(f"  [{split_name}] Skipping (no data)")
        return 0
    
    split_group = h5_file.create_group(split_name)
    
    # Get shapes from first sample
    H, W, C = images[0].shape  # C should be 4 for UNET1_2D
    N = len(images)
    
    # Create image dataset with chunking (allows append later)
    img_shape = (N, H, W, C)
    chunk_shape = (1, H, W, C)  # Chunk by individual sample for easy appending
    
    img_dset = split_group.create_dataset(
        'images',
        shape=img_shape,
        dtype=np.float32,
        chunks=chunk_shape,
        compression=COMPRESSION,
        compression_opts=COMPRESSION_OPTS,
        maxshape=(None, H, W, C)  # Allow growing along N dimension
    )
    
    # Create label dataset (same structure)
    lbl_shape = (N, H, W, 1)
    lbl_dset = split_group.create_dataset(
        'labels',
        shape=lbl_shape,
        dtype=np.float32,
        chunks=(1, H, W, 1),
        compression=COMPRESSION,
        compression_opts=COMPRESSION_OPTS,
        maxshape=(None, H, W, 1)
    )
    
    # Populate datasets
    for i, (img, lbl) in enumerate(zip(images, labels)):
        img_dset[i] = img
        lbl_dset[i] = lbl
    
    # Create metadata subgroup for hyperparameters
    meta_group = split_group.create_group('metadata')
    
    for i, params in enumerate(hyperparams):
        sample_meta = meta_group.create_group(f'sample_{i:06d}')
        for key, value in params.items():
            sample_meta.attrs[key] = value
    
    # Add split-level attributes
    split_group.attrs['n_samples'] = N
    split_group.attrs['image_shape'] = (H, W, C)
    split_group.attrs['label_shape'] = (H, W, 1)
    
    print(f"  [{split_name}] {N} samples ({100*N/(N+0):0.0f}%)")  # Will be corrected after totals
    return N


# ==============================================================================
# MAIN WORKFLOW
# ==============================================================================

def main():
    print("\n" + "="*80)
    print("CREATING HDF5 DATASETS FOR UNET1_2D (4-CHANNEL INPUT)")
    print("="*80 + "\n")
    
    # ============================================================
    # STEP 0: Validate input directories
    # ============================================================
    print("[PRE-CHECK] Validating input directories...\n")
    
    for path_name, path in [("MERGED", PATH_MERGED), ("GT_2D", PATH_GT_2D)]:
        if not os.path.exists(path):
            print(f"[ERROR] {path_name} directory not found: {path}")
            print(f"        Did you run loop_configuration_files.py first?")
            sys.exit(1)
        else:
            files = glob.glob(os.path.join(path, "*"))
            print(f"[OK] {path_name}: {len(files)} files found")
    
    # Create output directory
    Path(PATH_OUTPUT).mkdir(parents=True, exist_ok=True)
    
    # ============================================================
    # STEP 1: Scan and collect data
    # ============================================================
    print("\n[STEP 1] Scanning for MERGED_*.npy files...")
    print(f"         Directory: {PATH_MERGED}")
    
    merged_files = sorted(glob.glob(os.path.join(PATH_MERGED, "MERGED_*.npy")))
    print(f"         Found {len(merged_files)} files\n")
    
    if len(merged_files) == 0:
        print("[ERROR] No MERGED files found.")
        print("        Make sure loop_configuration_files.py completed successfully")
        print("        and produced MERGED_*.npy files in the merge step.")
        sys.exit(1)
    
    # ============================================================
    # STEP 2: Load and organize by resolution
    # ============================================================
    print("[STEP 2] Loading data and organizing by resolution...")
    print("         Extracting geometry parameters from filenames...")
    print("         Matching POCA data with ground truth...\n")
    
    # First, build a mapping of geometry bases to ground truth files
    # (geometry base = without the _Muons_XXXXX suffix)
    print("  [PRE-SCAN] Building ground truth file index...\n")
    gt_files = glob.glob(os.path.join(PATH_GT_2D, "*_ground_truth_density2D.npy"))
    gt_mapping = {}  # base_geometry -> ground_truth_file_path
    
    for gt_file in gt_files:
        # Extract geometry name from GT file
        # Format: <geom_name>_ground_truth_density2D.npy
        gt_basename = Path(gt_file).stem  # Remove .npy
        geom_from_gt = re.sub(r'_ground_truth_density2D$', '', gt_basename)
        gt_mapping[geom_from_gt] = gt_file
    
    print(f"  Found {len(gt_mapping)} ground truth files\n")
    
    # Dictionary: resolution_key -> { 'images': [], 'labels': [], 'hyperparams': [] }
    # Key insight: Files are grouped by resolution + muon count to ensure
    # that different noise levels (muon counts) are kept separate.
    resolution_groups = {}
    matched_count = 0
    missing_gt_count = 0
    
    for idx, merged_file in enumerate(merged_files, 1):
        filename = Path(merged_file).stem  # Remove extension
        
        # Extract geometry name (remove MERGED_ prefix and 2D/3D suffix)
        geom_name_with_muons = re.sub(r'^MERGED_', '', filename)
        geom_name_with_muons = re.sub(r'_(2D|3D)$', '', geom_name_with_muons)
        
        # Extract geometry WITHOUT the _Muons_XXXXX part for GT matching
        # Pattern: everything before _Muons_
        geom_name_base = re.sub(r'_Muons_\d+$', '', geom_name_with_muons)
        
        print(f"  [{idx}/{len(merged_files)}] {geom_name_base[:60]}...", end=" ", flush=True)
        
        # Parse hyperparameters (from full name including muons)
        hyperparams = parse_geometric_hyperparameters(geom_name_with_muons)
        
        if 'npx' not in hyperparams or 'npy' not in hyperparams:
            print("[SKIP] Could not extract resolution")
            missing_gt_count += 1
            continue
        
        npx = hyperparams['npx']
        npy = hyperparams['npy']
        
        # Create resolution key (resolution only, not muon count)
        # Muon count will be stored per-sample in metadata for traceability
        # This way: different noise levels → same H5, different n_muons_total values per sample
        # Model trains on data with variable noise, learns robustness
        n_muons = hyperparams.get('n_muons', TOTAL_MUONS_PER_SIMULATION)
        resolution_key = f"{npx}x{npy}x3"
        
        # Look up ground truth file
        if geom_name_base not in gt_mapping:
            print(f"[SKIP] No GT found")
            print(f"         Expected: {geom_name_base}_ground_truth_density2D.npy")
            missing_gt_count += 1
            continue
        
        gt_file_path = gt_mapping[geom_name_base]
        
        # Load sample pair
        image, label, success = load_sample_pair(merged_file, gt_file_path, geom_name_base)
        
        if not success:
            print("[FAIL]")
            missing_gt_count += 1
            continue
        
        # Validate resolution matches filename
        if image.shape != (npy, npx, 4):
            print(f"[SKIP] Shape mismatch: expected ({npy}, {npx}, 4), got {image.shape}")
            missing_gt_count += 1
            continue
        
        # Add to appropriate resolution group
        if resolution_key not in resolution_groups:
            resolution_groups[resolution_key] = {
                'images': [],
                'labels': [],
                'hyperparams': [],
                'geom_names': []
            }
        
        # CRITICAL METADATA: Total muons per simulation
        # IMPORTANT FOR TRACEABILITY: This value directly affects noise level
        # Different samples may have different n_muons_total values in same H5!
        # Use extracted value from filename, fallback to global constant
        if 'n_muons' in hyperparams:
            hyperparams['n_muons_total'] = hyperparams['n_muons']
        else:
            hyperparams['n_muons_total'] = TOTAL_MUONS_PER_SIMULATION
        
        # Ensure all critical metadata is preserved
        # These are essential for understanding each training sample
        hyperparams['material'] = hyperparams.get('material', 'unknown')
        hyperparams['word'] = hyperparams.get('word', 'unknown')
        hyperparams['stroke'] = hyperparams.get('stroke', 0)
        
        resolution_groups[resolution_key]['images'].append(image)
        resolution_groups[resolution_key]['labels'].append(label)
        resolution_groups[resolution_key]['hyperparams'].append(hyperparams)
        resolution_groups[resolution_key]['geom_names'].append(geom_name_base)
        
        print("[OK]")
        matched_count += 1
    
    print(f"\n  Summary:")
    print(f"    ✓ Matched: {matched_count} files")
    print(f"    ✗ Missing GT: {missing_gt_count} files")
    print(f"  Total resolutions found: {len(resolution_groups)}\n")
    
    if not resolution_groups:
        print("[ERROR] No valid data loaded.")
        print("        Check that:")
        print("        1. MERGED files are valid numpy files")
        print("        2. Ground truth files exist with matching geometry names")
        print("           (without the _Muons_XXXXX suffix)")
        print("        3. Resolution parameters are in filenames (_npx, _npy)")
        print("        4. MERGED and GT geometry names match (after removing _Muons_XXXXX)")
        sys.exit(1)
    
    # ============================================================
    # STEP 3: Create HDF5 file per resolution + muon count
    # ============================================================
    print("[STEP 3] Creating HDF5 files per resolution...\n")
    print("         One H5 file per (resolution, muon_count) combination")
    print("         This ensures datasets with 4 POCA channels are properly organized\n")
    
    for resolution_key, group_data in sorted(resolution_groups.items()):
        print(f"  Resolution: {resolution_key}")
        print(f"    Total samples: {len(group_data['images'])}")
        
        # Split data into train/val/test
        np.random.seed(RANDOM_SEED)
        n_total = len(group_data['images'])
        
        indices = np.arange(n_total)
        np.random.shuffle(indices)
        
        n_train = int(n_total * TRAIN_RATIO)
        n_val = int(n_total * VAL_RATIO)
        
        train_idx = indices[:n_train]
        val_idx = indices[n_train:n_train+n_val]
        test_idx = indices[n_train+n_val:]
        
        # Prepare data for each split
        splits = {
            'training': train_idx,
            'validation': val_idx,
            'test': test_idx
        }
        
        # Create HDF5 file (include total instance count in filename)
        h5_filename = f"{resolution_key}_{n_total}instances.h5"
        h5_filepath = os.path.join(PATH_OUTPUT, h5_filename)
        
        print(f"    Output: {h5_filename}")
        
        with h5py.File(h5_filepath, 'w') as h5file:
            total_samples = 0
            
            for split_name, split_indices in splits.items():
                split_images = [group_data['images'][i] for i in split_indices]
                split_labels = [group_data['labels'][i] for i in split_indices]
                split_hyperparams = [group_data['hyperparams'][i] for i in split_indices]
                
                n_samples = create_flexible_h5_split(
                    h5file, split_name,
                    split_images, split_labels, split_hyperparams
                )
                total_samples += n_samples
            
            # Add global metadata
            h5file.attrs['resolution'] = resolution_key
            h5file.attrs['total_samples'] = total_samples
            h5file.attrs['train_ratio'] = TRAIN_RATIO
            h5file.attrs['val_ratio'] = VAL_RATIO
            h5file.attrs['test_ratio'] = TEST_RATIO
            h5file.attrs['compression'] = COMPRESSION
            h5file.attrs['compression_opts'] = COMPRESSION_OPTS
            h5file.attrs['random_seed'] = RANDOM_SEED
            # Store muon count range for this H5 (may vary across samples!)
            muons_list = [hp.get('n_muons_total', TOTAL_MUONS_PER_SIMULATION) for hp in group_data['hyperparams']]
            h5file.attrs['n_muons_min'] = min(muons_list)
            h5file.attrs['n_muons_max'] = max(muons_list)
            h5file.attrs['n_muons_avg'] = int(sum(muons_list) / len(muons_list))
            h5file.attrs['has_mixed_muon_counts'] = len(set(muons_list)) > 1
            
            # Store geometry names as dataset
            h5file.create_dataset(
                'geometry_names',
                data=[n.encode('utf-8') for n in group_data['geom_names']]
            )
        
        file_size_mb = os.path.getsize(h5_filepath) / 1e6
        print(f"    File size: {file_size_mb:.1f} MB\n")
    
    # ============================================================
    # STEP 4: Summary and validation
    # ============================================================
    print("\n" + "="*80)
    print("[STEP 4] Final Validation and Summary")
    print("="*80 + "\n")
    
    h5_files = glob.glob(os.path.join(PATH_OUTPUT, "*.h5"))
    
    print(f"Created {len(h5_files)} H5 files:\n")
    
    for h5_path in sorted(h5_files):
        filename = Path(h5_path).name
        print(f"  {filename}:")
        
        with h5py.File(h5_path, 'r') as h5file:
            for split in ['training', 'validation', 'test']:
                if split in h5file:
                    n_samples = h5file[split].attrs['n_samples']
                    img_shape = tuple(h5file[split].attrs['image_shape'])
                    print(f"    /{split}: {n_samples} samples, shape {img_shape}")
    
    print("\n" + "="*80)
    print("✓ SUCCESSFULLY CREATED HDF5 DATASETS")
    print("="*80 + "\n")
    
    print(f"Output directory: {PATH_OUTPUT}\n")
    
    print("=" * 80)
    print("NEXT STEPS:")
    print("=" * 80)
    print(f"""
1. VERIFY DATASET:
   python3 << 'EOF'
   import h5py
   h5_path = "{PATH_OUTPUT}/128x128x4.h5"
   with h5py.File(h5_path, 'r') as f:
       print("Training images:", f['training/images'].shape)
       print("Training labels:", f['training/labels'].shape)
       print("Muon count range:", f.attrs['n_muons_min'], "-", f.attrs['n_muons_max'])
       print("Has mixed noise levels?", f.attrs['has_mixed_muon_counts'])
   EOF

2. ANALYZE METADATA DISTRIBUTION:
   python3 << 'EOF'
   import h5py
   h5_path = "{PATH_OUTPUT}/128x128x4.h5"
   with h5py.File(h5_path, 'r') as f:
       muons_list = []
       for i in range(min(50, f['training'].attrs['n_samples'])):
           n = f[f'training/metadata/sample_{{i:06d}}'].attrs['n_muons_total']
           muons_list.append(n)
       print("Sample muon counts:", set(muons_list))
   EOF

3. TRAIN UNET1_2D MODEL:
   python3 UNET1_2D.py
   
4. TO APPEND MORE DATA LATER:
   - Run loop_configuration_files1.py to generate new MERGED_*.npy files
   - Run merge_results_1.py to create 4-channel POCA data
   - Run this script again (it will add to existing H5 files)
   - Or manually extend with h5py:
     
     with h5py.File('128x128x4.h5', 'a') as f:
         n_current = f['training/images'].shape[0]
         f['training/images'].resize(n_current + n_new, axis=0)
         f['training/labels'].resize(n_current + n_new, axis=0)
         f['training/images'][n_current:] = new_images  # Shape: (10, 128, 128, 4)
         f['training/labels'][n_current:] = new_labels  # Shape: (10, 128, 128, 1)

5. ANALYZE DATASET COMPOSITION:
   python3 << 'EOF'
   import h5py
   h5_path = "{PATH_OUTPUT}/128x128x4.h5"
   with h5py.File(h5_path, 'r') as f:
       split_info = {{
           'train': (f['training/images'].shape[0], f['training/labels'].shape[0]),
           'validation': (f['validation/images'].shape[0], f['validation/labels'].shape[0]),
           'test': (f['test/images'].shape[0], f['test/labels'].shape[0])
       }}
       for split, (n_img, n_lbl) in split_info.items():
           print(f"{{split:12s}}: {{n_img:4d}} samples")
   EOF

6. MONITOR TRAINING:
   - Use TensorFlow callbacks to track validation metrics
   - Compare training on different muon count datasets
   - Check if n_muons_per_simulation correlates with training difficulty
""")
    
    return True


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n[INTERRUPTED] Dataset creation stopped by user.")
        print("[INFO] Partial H5 files may have been created in:", PATH_OUTPUT)
        sys.exit(1)
    except Exception as e:
        print(f"\n[FATAL ERROR] {str(e)}")
        print("[DEBUG] Full traceback:")
        import traceback
        traceback.print_exc()
        print("\nCommon issues:")
        print("  1. Insufficient disk space in", PATH_OUTPUT)
        print("  2. Corrupted MERGED_*.npy files")
        print("  3. Missing ground truth files")
        print("  4. Permission errors (check file ownership)")
        sys.exit(1)
